import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Pure Virgin Coconut Oil",
    price: 450,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Rasiya",
    image: "coconut_oil_atelier.png",
    tag: "100% NATURAL",
    description: "Premium cold-pressed virgin coconut oil extracted from fresh Kerala coconuts. Perfect for a healthy diet and natural hair care.",
    technicalSpecs: ["Cold-pressed extraction", "No added preservatives", "Rich in Lauric Acid"]
  },
  {
    id: "p2",
    name: "Customized Paper Bags",
    price: 120,
    category: "Paper Bags",
    parentCategory: "Pack Corner",
    maker: "Sheba",
    image: "Sheba - Customized Paper Bags.jpg",
    gallery: ["Sheba - Customized Paper Bags(1).jpg", "Sheba - Customized Paper Bags(2).jpg"],
    tag: "ECO-FRIENDLY",
    description: "Elegant, hand-crafted paper bags for premium gifting and sustainable packaging.",
    technicalSpecs: ["Biodegradable material", "Reinforced handles", "Custom sizes available"]
  },
  {
    id: "p3",
    name: "Nakshathra Idiyirachi",
    price: 380,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Nakshathra Spices",
    image: "Nakshathra Natural Spices.jpg",
    gallery: ["Sreeja Nakshathra - ഇടിയിറച്ചി.jpg"],
    tag: "TRADITIONAL",
    description: "Authentic Kerala style dried crushed meat (Idiyirachi) prepared with natural spices.",
    technicalSpecs: ["No artificial colors", "Traditional slow-drying", "FSSAI Certified"]
  },
  {
    id: "p4",
    name: "Handmade Peanut Cookies",
    price: 180,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Priya Tiju",
    image: "Priya Tiju Peanut Cookies.jpg",
    gallery: ["Priya Tiju.jpg", "Priya Tiju(1).jpg"],
    tag: "HOME BAKED",
    description: "Crunchy and delicious cookies loaded with roasted peanuts, baked in small batches.",
    technicalSpecs: ["Freshly baked", "High protein peanuts", "No trans fat"]
  },
  {
    id: "p5",
    name: "Vembada Beetroot Lip Balm",
    price: 150,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    maker: "Bhavana Baby",
    image: "IMG-20260329-WA0053.jpg",
    gallery: ["Bhavana Baby.jpg"],
    tag: "ORGANIC TINT",
    description: "Natural tinted lip balm infused with pure beetroot extracts for 24hr hydration.",
    technicalSpecs: ["Chemical-free", "Beetroot infused", "Organic oils"]
  },
  {
    id: "p6",
    name: "Sankupuzhpam Herbal Soap",
    price: 95,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    maker: "Meji K B",
    image: "Meji K B Sankupuzhpam soap.jpg",
    gallery: ["Meji K B.jpg", "Meji K B(1).jpg"],
    tag: "SKIN SAFE",
    description: "Handcrafted herbal soap enriched with Butterfly Pea (Sankupuzhpam) extracts.",
    technicalSpecs: ["Organic extracts", "Handmade", "Suitable for all skin types"]
  },
  {
    id: "p7",
    name: "Clean Shine Toilet Cleaner",
    price: 85,
    category: "Cleaning items",
    parentCategory: "Natural Care Zone",
    maker: "Mini Kumari",
    image: "Mini Kumari - Clean Shine.jpg",
    gallery: ["Mini Kumari - Clean Shine(1).jpg"],
    tag: "POWER CLEAN",
    description: "Powerful antibacterial toilet cleaner for deep cleaning and long-lasting hygiene.",
    technicalSpecs: ["Antibacterial formula", "Stain remover", "500ml pack"]
  },
  {
    id: "p8",
    name: "Clean Shine Dishwash Liquid",
    price: 65,
    category: "Cleaning items",
    parentCategory: "Natural Care Zone",
    maker: "Mini Kumari",
    image: "Mini Kumari- Clean Shine.jpg",
    tag: "LEMON FRESH",
    description: "Effective grease-cutting dishwash liquid with a refreshing lemon fragrance.",
    technicalSpecs: ["Ultra clean formula", "Skin safe", "Lemon power"]
  },
  {
    id: "p9",
    name: "Traditional Achappam",
    price: 140,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Vishnu Priya",
    image: "Vishnu Priya(2).jpg",
    gallery: ["Vishnu Priya.jpg", "Vishnu Priya(1).jpg"],
    tag: "CRUNCHY",
    description: "Crispy and light Kerala rose cookies made with pure coconut milk and rice flour.",
    technicalSpecs: ["Handmade", "No preservatives", "Traditional recipe"]
  },
  {
    id: "p10",
    name: "Premium Cashew Nuts",
    price: 850,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Soumya Nandan",
    image: "Soumya Nandan.jpg",
    tag: "W240 GRADE",
    description: "Large, whole, and white premium quality W240 grade cashew nuts from Kerala.",
    technicalSpecs: ["High in protein", "Natural kernels", "Vacuum packed"]
  },
  {
    id: "p11",
    name: "Designer Silk Check Saree",
    price: 2800,
    category: "Dress",
    parentCategory: "Fashion Street",
    maker: "Simi Ganesh",
    image: "Simi Ganesh.jpg",
    gallery: ["Simi Ganesh(1).jpg", "Simi Ganesh(2).jpg"],
    tag: "PREMIUM",
    description: "Exquisite silk saree with traditional golden check patterns and tassel finish.",
    technicalSpecs: ["Soft silk fabric", "Includes blouse piece", "Handloom style"]
  },
  {
    id: "p12",
    name: "Hybrid Vegetable Seeds Pack",
    price: 45,
    category: "teaching",
    parentCategory: "Service Zone",
    maker: "Sreeja Anil",
    image: "Sreeja Anil - Vegetable seeds.jpg",
    gallery: ["Sreeja Anil - Vegetable Seeds(1).jpg"],
    tag: "HOME GARDEN",
    description: "Assorted high-yield hybrid vegetable seeds suitable for home kitchen gardens.",
    technicalSpecs: ["High germination rate", "Hybrid variety", "Multi-variety pack"]
  },
  {
    id: "p13",
    name: "Hand-Woven Kasavu Saree",
    price: 3500,
    category: "Dress",
    parentCategory: "Fashion Street",
    maker: "Balaramapuram Weavers",
    image: "Simi Ganesh.jpg",
    gallery: ["Simi Ganesh.jpg", "Simi Ganesh(1).jpg", "Simi Ganesh(2).jpg"],
    tag: "HANDMADE",
    description: "Authentic Balaramapuram Kasavu saree with intricate gold zari work and pure cotton weave.",
    technicalSpecs: ["100% Pure Cotton", "Authentic Gold Zari", "Hand-loomed in Kerala"]
  },
  {
    id: "p14",
    name: "Traditional Brass Nilavilakku",
    price: 1850,
    category: "Corporate Gifts",
    parentCategory: "Gift Corner",
    maker: "Metals of Mannar",
    image: "brass_nilavilakku_atelier.png",
    tag: "BEST SELLER",
    description: "Masterfully hand-cast brass lamp, a symbol of heritage and tradition in every Kerala home.",
    technicalSpecs: ["Hand-cast pure brass", "Traditional multi-tier design", "Tarnish-resistant finish"]
  },
  {
    id: "p15",
    name: "Wild Forest Honey",
    price: 650,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Highrange Harvesters",
    image: "forest_honey_atelier.png",
    tag: "PURE",
    description: "Raw, unprocessed honey sourced from the deep forests of the Western Ghats.",
    technicalSpecs: ["Sustainably wild-harvested", "No added sugar", "Rich in natural enzymes"]
  },
  {
    id: "p16",
    name: "Home-Style Banana Chips",
    price: 240,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Mums Kitchen",
    image: "banana_chips_atelier.png",
    tag: "KERALA SPECIAL",
    description: "Crispy Nendran banana chips fried in pure coconut oil. The ultimate taste of Kerala.",
    technicalSpecs: ["Fried in 100% Coconut Oil", "Pure Nendran Bananas", "No artificial preservatives"]
  },
  {
    id: "p17",
    name: "Zen Yoga Mat",
    price: 75,
    category: "Yoga",
    parentCategory: "Service Zone",
    maker: "Prana Flow",
    image: "yoga_mat_atelier.png",
    tag: "ECO",
    description: "Eco-friendly, non-slip cork yoga mat for the ultimate grounding experience.",
    technicalSpecs: ["Sustainable Portuguese cork", "Non-slip grip surface", "Antimicrobial properties"]
  },
  {
    id: "p18",
    name: "Midnight Jasmine Perfume",
    price: 95,
    category: "Corporate Gifts",
    parentCategory: "Gift Corner",
    maker: "Essence de Paris",
    image: "jasmine_perfume_atelier.png",
    tag: "LUXURY",
    description: "A sophisticated evening scent with notes of blooming jasmine, vanilla, and musk.",
    technicalSpecs: ["Pure Jasmine absolute", "Long-lasting stay", "Glass flacon with gold detail"]
  },
  {
    id: "p19",
    name: "Organic Cotton Baby Set",
    price: 55,
    category: "Apparel",
    parentCategory: "Kids Zone",
    maker: "Tiny Threads",
    image: "baby_set_atelier.png",
    tag: "ORGANIC",
    description: "Ultra-soft GOTS certified organic cotton set for newborns.",
    technicalSpecs: ["GOTS Certified Cotton", "Hypoallergenic dyes", "Snap-button closures"]
  },
  {
    id: "p20",
    name: "Recycled Luxe Paper Bags",
    price: 15,
    category: "Paper Bags",
    parentCategory: "Pack Corner",
    maker: "Green Pack",
    image: "paper_bags_atelier.png",
    tag: "SUSTAINABLE",
    description: "Premium heavy-duty recycled paper bags with silk handles.",
    technicalSpecs: ["Heavy-duty recycled kraft", "Silk ribbon handles", "Reinforced bottom"]
  },
  {
    id: "p21",
    name: "Silk Minimalist Scarf",
    price: 85,
    category: "Jewellery",
    parentCategory: "Fashion Street",
    maker: "The Atelier",
    image: "https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?auto=format&fit=crop&q=80&w=800",
    tag: "SILK",
    description: "100% mulberry silk scarf with a hand-rolled hem and abstract print.",
    technicalSpecs: ["100% Mulberry silk", "Hand-rolled hems", "Digital print technology"]
  },
  {
    id: "p22",
    name: "Lavender Essential Oil",
    price: 28,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    maker: "Flora Botanica",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800",
    tag: "ORGANIC",
    description: "Pure, therapeutic-grade lavender essential oil for relaxation and skin care.",
    technicalSpecs: ["Steam distilled", "Therapeutic grade", "UV-protected glass bottle"]
  },
  {
    id: "p23",
    name: "Cold Pressed Olive Oil",
    price: 42,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Tuscan Essence",
    image: "olive_oil_atelier.png",
    tag: "ARTISANAL",
    description: "Extra virgin olive oil from ancient groves in Tuscany. Cold pressed for maximum nutrients.",
    technicalSpecs: ["First cold press", "Single-origin olives", "Acidity below 0.8%"]
  },
  {
    id: "p24",
    name: "Geometric Glass Bottle Trio",
    price: 65,
    category: "Bottles",
    parentCategory: "Pack Corner",
    maker: "Vitreous Crafts",
    image: "glass_bottles_atelier.png",
    tag: "GLASS",
    description: "Three sculptural glass bottles with bamboo stoppers. Perfect for pantry or vanity.",
    technicalSpecs: ["BPA-free lead-free glass", "Bamboo airtight seals", "Set of 3 variant sizes"]
  },
  {
    id: "p25",
    name: "Midnight Velvet Evening Gown",
    price: 850,
    category: "Dress",
    parentCategory: "Fashion Street",
    maker: "The Atelier",
    image: "velvet_gown_atelier.png",
    tag: "COUTURE",
    description: "A show-stopping evening gown crafted from Italian silk velvet. Features a minimalist silhouette and a discreet side slit.",
    technicalSpecs: ["Italian Silk Velvet", "Hidden seam pockets", "Structured corset bodice"]
  },
  {
    id: "p26",
    name: "Minimal Silver Cuff",
    price: 120,
    category: "Jewellery",
    parentCategory: "Fashion Street",
    maker: "Aurelius",
    image: "silver_cuff_atelier.png",
    tag: "HANDCRAFTED",
    description: "Solid sterling silver cuff with a hand-brushed matte finish. A perfect balance of strength and elegance.",
    technicalSpecs: ["925 Sterling Silver", "Matte brushed finish", "Adjustable open band"]
  },
  {
    id: "p27",
    name: "Organic Quinoa Blend",
    price: 24,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Ancient Grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
    tag: "SUPERFOOD",
    description: "A nutrient-dense blend of red, white, and black quinoa. Sourced from sustainable high-altitude farms.",
    technicalSpecs: ["Triple-washed grains", "Source of 9 amino acids", "Organic certified"]
  },
  {
    id: "p28",
    name: "Artisan Dark Chocolate",
    price: 18,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    maker: "Noir Botanica",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&q=80&w=800",
    tag: "BEAN-TO-BAR",
    description: "75% single-origin cacao from Madagascar. Notes of red fruit and toasted nuts.",
    technicalSpecs: ["75% single-origin cacao", "Ethically sourced beans", "Stone-ground texture"]
  },
  {
    id: "p29",
    name: "Rose Water Facial Mist",
    price: 32,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    maker: "Flora Botanica",
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=800",
    tag: "PURE",
    description: "Pure steam-distilled Damask rose water. Instantly hydrates and refreshes tired skin.",
    technicalSpecs: ["Damask rose petals", "Non-alcoholic formula", "Mist spray head"]
  },
  {
    id: "p30",
    name: "Eco-Friendly Bamboo Toothbrush Set",
    price: 12,
    category: "Cleaning items",
    parentCategory: "Natural Care Zone",
    maker: "Green Pack",
    image: "toothbrush_set_atelier.png",
    tag: "PLASTIC-FREE",
    description: "Set of 4 biodegradable bamboo toothbrushes with charcoal-infused bristles.",
    technicalSpecs: ["Biodegradable bamboo", "Charcoal-infused bristles", "Set of 4"]
  },
  {
    id: "p31",
    name: "Executive Leather Notebook",
    price: 55,
    category: "Corporate Gifts",
    parentCategory: "Gift Corner",
    maker: "The Scribe",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=800",
    tag: "BESPOKE",
    description: "Refillable Italian leather notebook with premium cream paper. An essential for the modern professional.",
    technicalSpecs: ["Full-grain Italian leather", "120gsm archival paper", "Refillable design"]
  },
  {
    id: "p32",
    name: "Customized Ceramic Mug Set",
    price: 45,
    category: "Personalized",
    parentCategory: "Gift Corner",
    maker: "Clay & Coil",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800",
    tag: "UNIQUE",
    description: "Hand-thrown ceramic mugs with minimalist gold-leaf initials. Set of two.",
    technicalSpecs: ["Oven & Microwave safe", "Hand-brushed gold initials", "Matte ceramic finish"]
  },
  {
    id: "p33",
    name: "Wooden Alphabet Blocks",
    price: 38,
    category: "Toys",
    parentCategory: "Kids Zone",
    maker: "Arul Woodworks",
    image: "https://images.unsplash.com/photo-1535572290543-960a8046f5af?auto=format&fit=crop&q=80&w=800",
    tag: "HEIRLOOM",
    description: "Hand-carved maple wood blocks finished with non-toxic beeswax. A timeless educational tool.",
    technicalSpecs: ["Solid Maple wood", "Food-grade beeswax finish", "Engraved letters"]
  },
  {
    id: "p34",
    name: "Organic Cotton Hoodie",
    price: 65,
    category: "Apparel",
    parentCategory: "Kids Zone",
    maker: "Tiny Threads",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800",
    tag: "COZY",
    description: "Extra-thick organic cotton fleece hoodie. Designed for comfort and durability.",
    technicalSpecs: ["Organic french terry", "Heavyweight 400gsm", "Plant-based dyes"]
  },
  {
    id: "p35",
    name: "Mindfulness Coaching Session",
    price: 150,
    category: "Counselling",
    parentCategory: "Service Zone",
    maker: "Prana Flow",
    image: "https://images.unsplash.com/photo-1528319725582-ddc096101511?auto=format&fit=crop&q=80&w=800",
    tag: "INSTITUTIONAL",
    description: "One-hour private session with a certified mindfulness practitioner. Focused on stress reduction and focus.",
    technicalSpecs: ["Certified practitioner", "Individual focus plan", "Post-session toolkit"]
  },
  {
    id: "p36",
    name: "Advanced Yoga Block",
    price: 25,
    category: "Yoga",
    parentCategory: "Service Zone",
    maker: "Prana Flow",
    image: "yoga_block_atelier.png",
    tag: "PERFORMANCE",
    description: "High-density foam block for deeper stretches and improved alignment.",
    technicalSpecs: ["Recycled high-density foam", "Chamfered edges", "Stable support"]
  },
  {
    id: "p37",
    name: "Insulated Copper Bottle",
    price: 45,
    category: "Bottles",
    parentCategory: "Pack Corner",
    maker: "Vitreous Crafts",
    image: "copper_bottle_atelier.png",
    tag: "TRADITIONAL",
    description: "Hand-hammered pure copper bottle. Known for its Ayurvedic health benefits and superior insulation.",
    technicalSpecs: ["99.9% pure copper", "Airtight leakproof cap", "Hand-hammered texture"]
  },
  {
    id: "p38",
    name: "Organic Cotton Tote Bag",
    price: 22,
    category: "Covers",
    parentCategory: "Pack Corner",
    maker: "Green Pack",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800",
    tag: "REUSABLE",
    description: "Heavy-duty canvas tote with reinforced handles. A premium alternative to plastic.",
    technicalSpecs: ["12oz Heavy canvas", "Cross-stitched handles", "Internal pocket"]
  }
];

export const CATEGORIES = [
  { 
    name: "Fashion Street", 
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Dress", "Jewellery"]
  },
  { 
    name: "Healthy Kitchen", 
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Food Products"]
  },
  { 
    name: "Natural Care Zone", 
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Cosmetics", "Cleaning items"]
  },
  { 
    name: "Gift Corner", 
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Corporate Gifts", "Personalized"]
  },
  { 
    name: "Kids Zone", 
    image: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Toys", "Apparel"]
  },
  { 
    name: "Service Zone", 
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Yoga", "teaching", "Counselling"]
  },
  { 
    name: "Pack Corner", 
    image: "https://images.unsplash.com/photo-1620987278429-ca1cf2f51df2?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Bottles", "Covers", "Paper Bags"]
  }
];
