import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Pure Virgin Coconut Oil",
    price: 450.0,
    category: "Natural Care",
    parentCategory: "Natural Care Zone",
    description: "Cold-pressed from fresh Kerala coconuts. 100% natural, chemical-free, and nutrient-rich.",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    tag: "KERALA SPECIAL",
    material: "Oil",
    color: "Clear",
    artisan: "Kerala Roots",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "2",
    name: "Hand-Woven Kasavu Saree",
    price: 3500.0,
    category: "Traditional",
    parentCategory: "Fashion Street",
    description: "Authentic Balaramapuram Kasavu saree with intricate gold zari work and pure cotton weave.",
    image: "https://images.unsplash.com/photo-1610030469668-935142b96fe4?auto=format&fit=crop&q=80&w=800",
    tag: "HANDMADE",
    material: "Cotton",
    color: "Cream & Gold",
    artisan: "The Weaver Colony",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1610030469668-935142b96fe4?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "3",
    name: "Traditional Brass Nilavilakku",
    price: 1850.0,
    category: "Home Decor",
    parentCategory: "Gift Corner",
    description: "Masterfully hand-cast brass lamp, a symbol of heritage and tradition in every Kerala home.",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800",
    tag: "BEST SELLER",
    material: "Brass",
    color: "Gold",
    artisan: "Metals of Mannar",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "4",
    name: "Wild Forest Honey",
    price: 650.0,
    category: "Food",
    parentCategory: "Healthy Kitchen",
    description: "Raw, unprocessed honey sourced from the deep forests of the Western Ghats.",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800",
    tag: "PURE",
    material: "Honey",
    color: "Deep Amber",
    artisan: "Highrange Harvesters",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "16",
    name: "Home-Style Banana Chips",
    price: 240.0,
    category: "Snacks",
    parentCategory: "Healthy Kitchen",
    description: "Crispy Nendran banana chips fried in pure coconut oil. The ultimate taste of Kerala.",
    image: "https://images.unsplash.com/photo-1590080875515-8a03b1447d9c?auto=format&fit=crop&q=80&w=800",
    tag: "KERALA SPECIAL",
    material: "Banana",
    color: "Yellow",
    artisan: "Mums Kitchen",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1590080875515-8a03b1447d9c?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "5",
    name: "Zen Yoga Mat",
    price: 75.0,
    category: "Yoga",
    parentCategory: "Service Zone",
    description: "Eco-friendly, non-slip cork yoga mat for the ultimate grounding experience.",
    image: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&q=80&w=800",
    tag: "ECO",
    material: "Cork",
    color: "Natural",
    artisan: "Prana Flow",
    rating: 4.8,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "6",
    name: "Midnight Jasmine Perfume",
    price: 95.0,
    category: "Gifts",
    parentCategory: "Gift Corner",
    description: "A sophisticated evening scent with notes of blooming jasmine, vanilla, and musk.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800",
    tag: "LUXURY",
    material: "Liquid",
    color: "Amber",
    artisan: "Essence de Paris",
    rating: 4.9,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "7",
    name: "Organic Cotton Baby Set",
    price: 55.0,
    category: "Kids Zone",
    parentCategory: "Kids Zone",
    description: "Ultra-soft GOTS certified organic cotton set for newborns.",
    image: "https://images.unsplash.com/photo-1555009393-f20bdb245c4d?auto=format&fit=crop&q=80&w=800",
    tag: "ORGANIC",
    material: "Cotton",
    color: "Soft White",
    artisan: "Tiny Threads",
    rating: 4.7,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1555009393-f20bdb245c4d?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "8",
    name: "Recycled Luxe Paper Bags",
    price: 15.0,
    category: "Paper Bags",
    parentCategory: "Pack Corner",
    description: "Premium heavy-duty recycled paper bags with silk handles.",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800",
    tag: "SUSTAINABLE",
    material: "Paper",
    color: "Kraft",
    artisan: "Green Pack",
    rating: 4.6,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "9",
    name: "Silk Minimalist Scarf",
    price: 85.0,
    category: "Jewellery",
    parentCategory: "Fashion Street",
    description: "100% mulberry silk scarf with a hand-rolled hem and abstract print.",
    image: "https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?auto=format&fit=crop&q=80&w=800",
    tag: "SILK",
    material: "Silk",
    color: "Champagne",
    artisan: "The Atelier",
    rating: 4.8,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "10",
    name: "Lavender Essential Oil",
    price: 28.0,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    description: "Pure, therapeutic-grade lavender essential oil for relaxation and skin care.",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800",
    tag: "ORGANIC",
    material: "Oil",
    color: "Purple",
    artisan: "Flora Botanica",
    rating: 4.9,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "11",
    name: "Cold Pressed Olive Oil",
    price: 42.0,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    description: "Extra virgin olive oil from ancient groves in Tuscany. Cold pressed for maximum nutrients.",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbadcbaf?auto=format&fit=crop&q=80&w=800",
    tag: "ARTISANAL",
    material: "Oil",
    color: "Green Gold",
    artisan: "Tuscan Essence",
    rating: 5.0,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbadcbaf?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "12",
    name: "Geometric Glass Bottle Trio",
    price: 65.0,
    category: "Bottles",
    parentCategory: "Pack Corner",
    description: "Three sculptural glass bottles with bamboo stoppers. Perfect for pantry or vanity.",
    image: "https://images.unsplash.com/photo-1602143328230-019672729938?auto=format&fit=crop&q=80&w=800",
    tag: "GLASS",
    material: "Glass",
    color: "Clear",
    artisan: "Vitreous",
    rating: 4.7,
    inStock: true,
    images: [
      "https://images.unsplash.com/photo-1602143328230-019672729938?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "13",
    name: "Midnight Velvet Evening Gown",
    price: 850.0,
    category: "Dress",
    parentCategory: "Fashion Street",
    description: "A show-stopping evening gown crafted from Italian silk velvet. Features a minimalist silhouette and a discreet side slit.",
    image: "https://images.unsplash.com/photo-1539109132314-34a95dad7014?auto=format&fit=crop&q=80&w=800",
    tag: "COUTURE",
    material: "Silk Velvet",
    color: "Midnight Blue",
    artisan: "The Atelier",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1539109132314-34a95dad7014?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "14",
    name: "Minimal Silver Cuff",
    price: 120.0,
    category: "Jewellery",
    parentCategory: "Fashion Street",
    description: "Solid sterling silver cuff with a hand-brushed matte finish. A perfect balance of strength and elegance.",
    image: "https://images.unsplash.com/photo-1611591437318-193425f38936?auto=format&fit=crop&q=80&w=800",
    tag: "HANDCRAFTED",
    material: "925 Silver",
    color: "Silver",
    artisan: "Aurelius",
    rating: 4.8,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1611591437318-193425f38936?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "15",
    name: "Organic Quinoa Blend",
    price: 24.0,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    description: "A nutrient-dense blend of red, white, and black quinoa. Sourced from sustainable high-altitude farms.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
    tag: "SUPERFOOD",
    material: "Quinoa",
    color: "Multicolor",
    artisan: "Ancient Grains",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "27",
    name: "Artisan Dark Chocolate",
    price: 18.0,
    category: "Food Products",
    parentCategory: "Healthy Kitchen",
    description: "75% single-origin cacao from Madagascar. Notes of red fruit and toasted nuts.",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&q=80&w=800",
    tag: "BEAN-TO-BAR",
    material: "Cacao",
    color: "Dark Brown",
    artisan: "Noir Botanica",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "17",
    name: "Rose Water Facial Mist",
    price: 32.0,
    category: "Cosmetics",
    parentCategory: "Natural Care Zone",
    description: "Pure steam-distilled Damask rose water. Instantly hydrates and refreshes tired skin.",
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=800",
    tag: "PURE",
    material: "Liquid",
    color: "Clear",
    artisan: "Flora Botanica",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "18",
    name: "Eco-Friendly Bamboo Toothbrush Set",
    price: 12.0,
    category: "Cleaning items",
    parentCategory: "Natural Care Zone",
    description: "Set of 4 biodegradable bamboo toothbrushes with charcoal-infused bristles.",
    image: "https://images.unsplash.com/photo-1607613061617-6ff5677502ed?auto=format&fit=crop&q=80&w=800",
    tag: "PLASTIC-FREE",
    material: "Bamboo",
    color: "Natural",
    artisan: "Green Pack",
    rating: 4.7,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1607613061617-6ff5677502ed?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "19",
    name: "Executive Leather Notebook",
    price: 55.0,
    category: "Corporate Gifts",
    parentCategory: "Gift Corner",
    description: "Refillable Italian leather notebook with premium cream paper. An essential for the modern professional.",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=800",
    tag: "BESPOKE",
    material: "Grain Leather",
    color: "Cognac",
    artisan: "The Scribe",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "20",
    name: "Customized Ceramic Mug Set",
    price: 45.0,
    category: "Personalized",
    parentCategory: "Gift Corner",
    description: "Hand-thrown ceramic mugs with minimalist gold-leaf initials. Set of two.",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800",
    tag: "UNIQUE",
    material: "Ceramic",
    color: "Speckled White",
    artisan: "Clay & Coil",
    rating: 4.8,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "21",
    name: "Wooden Alphabet Blocks",
    price: 38.0,
    category: "Toys",
    parentCategory: "Kids Zone",
    description: "Hand-carved maple wood blocks finished with non-toxic beeswax. A timeless educational tool.",
    image: "https://images.unsplash.com/photo-1535572290543-960a8046f5af?auto=format&fit=crop&q=80&w=800",
    tag: "HEIRLOOM",
    material: "Maple Wood",
    color: "Natural",
    artisan: "Tiny Threads",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1535572290543-960a8046f5af?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "22",
    name: "Organic Cotton Hoodie",
    price: 65.0,
    category: "Apparel",
    parentCategory: "Kids Zone",
    description: "Extra-thick organic cotton fleece hoodie. Designed for comfort and durability.",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800",
    tag: "COZY",
    material: "Organic Cotton",
    color: "Heather Grey",
    artisan: "Tiny Threads",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "23",
    name: "Mindfulness Coaching Session",
    price: 150.0,
    category: "Counselling",
    parentCategory: "Service Zone",
    description: "One-hour private session with a certified mindfulness practitioner. Focused on stress reduction and focus.",
    image: "https://images.unsplash.com/photo-1528319725582-ddc096101511?auto=format&fit=crop&q=80&w=800",
    tag: "INSTITUTIONAL",
    material: "Digital/In-Person",
    color: "N/A",
    artisan: "Prana Flow",
    rating: 5.0,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1528319725582-ddc096101511?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "24",
    name: "Advanced Yoga Block",
    price: 25.0,
    category: "Yoga",
    parentCategory: "Service Zone",
    description: "High-density foam block for deeper stretches and improved alignment.",
    image: "https://images.unsplash.com/photo-1518611012118-2969c63b07b7?auto=format&fit=crop&q=80&w=800",
    tag: "PERFORMANCE",
    material: "Foam",
    color: "Indigo",
    artisan: "Prana Flow",
    rating: 4.7,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1518611012118-2969c63b07b7?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "25",
    name: "Insulated Copper Bottle",
    price: 45.0,
    category: "Bottles",
    parentCategory: "Pack Corner",
    description: "Hand-hammered pure copper bottle. Known for its Ayurvedic health benefits and superior insulation.",
    image: "https://images.unsplash.com/photo-1610832309325-1ef61245a498?auto=format&fit=crop&q=80&w=800",
    tag: "TRADITIONAL",
    material: "Copper",
    color: "Copper",
    artisan: "Vitreous",
    rating: 4.9,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1610832309325-1ef61245a498?auto=format&fit=crop&q=80&w=800"]
  },
  {
    id: "26",
    name: "Organic Cotton Tote Bag",
    price: 22.0,
    category: "Covers",
    parentCategory: "Pack Corner",
    description: "Heavy-duty canvas tote with reinforced handles. A premium alternative to plastic.",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800",
    tag: "REUSABLE",
    material: "Organic Canvas",
    color: "Natural White",
    artisan: "Green Pack",
    rating: 4.8,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800"]
  }
];

export const CATEGORIES = [
  { 
    name: "Fashion Street", 
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Dress", "Jewellery"]
  },
  { 
    name: "Healthy Kitchen", 
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Food Products"]
  },
  { 
    name: "Natural Care Zone", 
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Cosmetics", "Cleaning items"]
  },
  { 
    name: "Gift Corner", 
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Corporate Gifts", "Personalized"]
  },
  { 
    name: "Kids Zone", 
    image: "https://images.unsplash.com/photo-1515488442463-5af462e499e9?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Toys", "Apparel"]
  },
  { 
    name: "Service Zone", 
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Yoga", "Teaching", "Counselling"]
  },
  { 
    name: "Pack Corner", 
    image: "https://images.unsplash.com/photo-1620987278429-ca1cf2f51df2?auto=format&fit=crop&q=80&w=1000",
    subcategories: ["Bottles", "Covers", "Paper Bags"]
  }
];
